### ISSUE TITLE
Issue#1

### ISSUE THREAD

**Issue by vladkaryakin** [YuriiMatsiv/Mobile-App#1]
https://github.com/YuriiMatsiv/Mobile-App/blob/9d219db3bc1ba24565135403b58152bc1da58e0e/src/index.html#L12
1)Создай лучше section
2)Если ты создаешь class, то он должен в названии нести то, что касается непосредственно этого блока , firstPage - первая страница,а  у тебя это первая секция, первый блок , но никак не страница.

**Comment by YuriiMatsiv** [comment]
Поміняв.
