### ISSUE TITLE
Two sections in one <div>

### ISSUE THREAD

**Issue by vladkaryakin** [YuriiMatsiv/Mobile-App#4]
https://github.com/YuriiMatsiv/Mobile-App/blob/9d219db3bc1ba24565135403b58152bc1da58e0e/src/index.html#L85-L122

На 114 строке должен заканчиваться твой div и начинаться новый со 114 - 121, у тебя всё в одном div c классом sixPage

**Comment by YuriiMatsiv** [comment]
Додав ще одну секцію
