### ISSUE TITLE
not valid tag

### ISSUE THREAD

**Issue by vladkaryakin** [YuriiMatsiv/Mobile-App#6]
https://github.com/YuriiMatsiv/Mobile-App/blob/9d219db3bc1ba24565135403b58152bc1da58e0e/src/index.html#L135-L140

https://caniuse.com/#search=menu
лучше используй обычный ul

**Comment by YuriiMatsiv** [comment]
замінив menu на ul . та помістив їх в тег nav...

**Comment by YuriiMatsiv** [comment]
Чи краще залишити просто ul?

**Comment by vladkaryakin** [comment]
Можешь оставить и с nav
