### ISSUE TITLE
Unneeded use of <p> in all cases

### ISSUE THREAD

**Issue by vladkaryakin** [YuriiMatsiv/Mobile-App#8]
https://github.com/YuriiMatsiv/Mobile-App/blob/f4ad0186e348a1c8a8509210fe5542d64eef5c65/src/index.html#L21-L27

1)Arsenal vs Chelsea - should be a heading
2) Sat 12:35 Pm - date without using p
3)Friendly match can be either p or span

**Comment by YuriiMatsiv** [comment]
не зовсім зрозумів з "часом"... але якось підправив...

**Comment by vladkaryakin** [comment]
Обновил issue
